package cloudflared

import (
	"errors"
	"fmt"
	"net"
	"strconv"
	"strings"
	"time"
)

const (
	defaultStandaloneMetricsAddress    = "127.0.0.1:20241"
	defaultStandaloneLogLevel          = "info"
	defaultStandaloneTransportLogLevel = "warn"
	defaultStandaloneProtocol          = "auto"
	defaultStandaloneEdgeIPVersion     = "auto"
	defaultStandaloneRetries           = 5
	defaultStandaloneGracePeriod       = 30 * time.Second
)

// StandaloneConfig is the token-free cloudflared runtime configuration emitted
// for operators who intentionally run cloudflared without tunnel-client.
//
// TokenFile is a path only. The generator never reads or embeds the tunnel
// token, so the rendered config is safe to check into deployment manifests.
type StandaloneConfig struct {
	TokenFile         string
	MetricsAddress    string
	LogLevel          string
	TransportLogLevel string
	Protocol          string
	EdgeIPVersion     string
	Retries           int
	GracePeriod       time.Duration
}

// DefaultStandaloneConfig returns the reviewed production defaults for a
// directly supervised cloudflared process.
func DefaultStandaloneConfig(tokenFile string) StandaloneConfig {
	return StandaloneConfig{
		TokenFile:         tokenFile,
		MetricsAddress:    defaultStandaloneMetricsAddress,
		LogLevel:          defaultStandaloneLogLevel,
		TransportLogLevel: defaultStandaloneTransportLogLevel,
		Protocol:          defaultStandaloneProtocol,
		EdgeIPVersion:     defaultStandaloneEdgeIPVersion,
		Retries:           defaultStandaloneRetries,
		GracePeriod:       defaultStandaloneGracePeriod,
	}
}

// RenderStandaloneConfig renders a deterministic cloudflared YAML config that
// keeps the tunnel token out of argv and out of the config file itself.
func RenderStandaloneConfig(cfg StandaloneConfig) ([]byte, error) {
	if err := cfg.validate(); err != nil {
		return nil, err
	}

	var out strings.Builder
	out.WriteString("# Generated by tunnel-client cloudflared config.\n")
	out.WriteString("# Token-free by design: the file references a token path but never embeds the token.\n")
	out.WriteString("# Run directly with: cloudflared tunnel --config /etc/cloudflared/config.yml run\n")
	fmt.Fprintf(&out, "token-file: %s\n", yamlQuotedString(cfg.TokenFile))
	out.WriteString("no-autoupdate: true\n")
	fmt.Fprintf(&out, "metrics: %s\n", yamlQuotedString(cfg.MetricsAddress))
	fmt.Fprintf(&out, "loglevel: %s\n", yamlQuotedString(cfg.LogLevel))
	fmt.Fprintf(&out, "transport-loglevel: %s\n", yamlQuotedString(cfg.TransportLogLevel))
	fmt.Fprintf(&out, "protocol: %s\n", yamlQuotedString(cfg.Protocol))
	fmt.Fprintf(&out, "edge-ip-version: %s\n", yamlQuotedString(cfg.EdgeIPVersion))
	fmt.Fprintf(&out, "retries: %d\n", cfg.Retries)
	fmt.Fprintf(&out, "grace-period: %s\n", yamlQuotedString(cfg.GracePeriod.String()))
	return []byte(out.String()), nil
}

func (cfg StandaloneConfig) validate() error {
	tokenFile := strings.TrimSpace(cfg.TokenFile)
	if tokenFile == "" {
		return errors.New("cloudflared config: --token-file is required")
	}
	if err := validateStandaloneScalar("token-file", tokenFile); err != nil {
		return err
	}

	metricsAddress := strings.TrimSpace(cfg.MetricsAddress)
	if err := validateMetricsAddress(metricsAddress); err != nil {
		return err
	}
	if err := validateStandaloneChoice("log-level", cfg.LogLevel, "debug", "info", "warn", "error", "fatal"); err != nil {
		return err
	}
	if err := validateStandaloneChoice("transport-log-level", cfg.TransportLogLevel, "debug", "info", "warn", "error", "fatal"); err != nil {
		return err
	}
	if err := validateStandaloneChoice("protocol", cfg.Protocol, "auto", "http2", "quic"); err != nil {
		return err
	}
	if err := validateStandaloneChoice("edge-ip-version", cfg.EdgeIPVersion, "auto", "4", "6"); err != nil {
		return err
	}
	if cfg.Retries < 0 {
		return errors.New("cloudflared config: --retries must be non-negative")
	}
	if cfg.GracePeriod <= 0 {
		return errors.New("cloudflared config: --grace-period must be positive")
	}
	return nil
}

func validateMetricsAddress(address string) error {
	if err := validateStandaloneScalar("metrics-address", address); err != nil {
		return err
	}
	host, port, err := net.SplitHostPort(address)
	if err != nil {
		return fmt.Errorf("cloudflared config: invalid --metrics-address: %w", err)
	}
	if strings.TrimSpace(host) == "" {
		return errors.New("cloudflared config: --metrics-address must include a host")
	}
	portNumber, err := strconv.Atoi(port)
	if err != nil || portNumber < 1 || portNumber > 65535 {
		return errors.New("cloudflared config: --metrics-address port must be between 1 and 65535")
	}
	return nil
}

func validateStandaloneChoice(name, value string, allowed ...string) error {
	value = strings.TrimSpace(value)
	if err := validateStandaloneScalar(name, value); err != nil {
		return err
	}
	for _, candidate := range allowed {
		if value == candidate {
			return nil
		}
	}
	return fmt.Errorf("cloudflared config: invalid --%s %q; expected one of %s", name, value, strings.Join(allowed, ", "))
}

func validateStandaloneScalar(name, value string) error {
	if strings.TrimSpace(value) == "" {
		return fmt.Errorf("cloudflared config: --%s must not be empty", name)
	}
	if strings.ContainsAny(value, "\x00\r\n") {
		return fmt.Errorf("cloudflared config: --%s must be a single line", name)
	}
	return nil
}

func yamlQuotedString(value string) string {
	return strconv.Quote(strings.TrimSpace(value))
}
