package cloudflared

import (
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestRenderStandaloneConfigUsesTokenFreeProductionDefaults(t *testing.T) {
	t.Parallel()

	got, err := RenderStandaloneConfig(DefaultStandaloneConfig("/run/secrets/cloudflared/token"))
	require.NoError(t, err)
	require.Equal(t, strings.Join([]string{
		"# Generated by tunnel-client cloudflared config.",
		"# Token-free by design: the file references a token path but never embeds the token.",
		"# Run directly with: cloudflared tunnel --config /etc/cloudflared/config.yml run",
		`token-file: "/run/secrets/cloudflared/token"`,
		"no-autoupdate: true",
		`metrics: "127.0.0.1:20241"`,
		`loglevel: "info"`,
		`transport-loglevel: "warn"`,
		`protocol: "auto"`,
		`edge-ip-version: "auto"`,
		"retries: 5",
		`grace-period: "30s"`,
		"",
	}, "\n"), string(got))
	require.NotContains(t, string(got), "TUNNEL_TOKEN=")
}

func TestRenderStandaloneConfigEscapesPathAndAcceptsOverrides(t *testing.T) {
	t.Parallel()

	cfg := DefaultStandaloneConfig(`/run/secrets/cloudflared/"token"`)
	cfg.MetricsAddress = "localhost:32123"
	cfg.LogLevel = "warn"
	cfg.TransportLogLevel = "error"
	cfg.Protocol = "http2"
	cfg.EdgeIPVersion = "4"
	cfg.Retries = 0
	cfg.GracePeriod = 45 * time.Second

	got, err := RenderStandaloneConfig(cfg)
	require.NoError(t, err)
	require.Contains(t, string(got), "token-file: "+yamlQuotedString(cfg.TokenFile))
	require.Contains(t, string(got), `metrics: "localhost:32123"`)
	require.Contains(t, string(got), `loglevel: "warn"`)
	require.Contains(t, string(got), `transport-loglevel: "error"`)
	require.Contains(t, string(got), `protocol: "http2"`)
	require.Contains(t, string(got), `edge-ip-version: "4"`)
	require.Contains(t, string(got), "retries: 0")
	require.Contains(t, string(got), `grace-period: "45s"`)
}

func TestRenderStandaloneConfigRejectsUnsafeOrUnsupportedValues(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		mutate  func(*StandaloneConfig)
		message string
	}{
		{
			name:    "missing token file",
			mutate:  func(cfg *StandaloneConfig) { cfg.TokenFile = "" },
			message: "--token-file is required",
		},
		{
			name:    "multiline token file",
			mutate:  func(cfg *StandaloneConfig) { cfg.TokenFile = "/run/secrets/token\nsecret" },
			message: "--token-file must be a single line",
		},
		{
			name:    "invalid metrics address",
			mutate:  func(cfg *StandaloneConfig) { cfg.MetricsAddress = "127.0.0.1" },
			message: "invalid --metrics-address",
		},
		{
			name:    "missing metrics host",
			mutate:  func(cfg *StandaloneConfig) { cfg.MetricsAddress = ":20241" },
			message: "--metrics-address must include a host",
		},
		{
			name:    "invalid log level",
			mutate:  func(cfg *StandaloneConfig) { cfg.LogLevel = "trace" },
			message: "invalid --log-level",
		},
		{
			name:    "invalid protocol",
			mutate:  func(cfg *StandaloneConfig) { cfg.Protocol = "udp" },
			message: "invalid --protocol",
		},
		{
			name:    "negative retries",
			mutate:  func(cfg *StandaloneConfig) { cfg.Retries = -1 },
			message: "--retries must be non-negative",
		},
		{
			name:    "zero grace period",
			mutate:  func(cfg *StandaloneConfig) { cfg.GracePeriod = 0 },
			message: "--grace-period must be positive",
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			cfg := DefaultStandaloneConfig("/run/secrets/cloudflared/token")
			tt.mutate(&cfg)
			_, err := RenderStandaloneConfig(cfg)
			require.Error(t, err)
			require.Contains(t, err.Error(), tt.message)
		})
	}
}
