#!/usr/bin/env bash
set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly RELEASE_TAG_SCRIPT="${SCRIPT_DIR}/release_tag.sh"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/generate_homebrew_formula.sh \
    --tag <release-tag> \
    --checksums <SHA256SUMS.txt> \
    --output <formula.rb> \
    [--allow-prerelease]

Generates the openai/tools tap formula for a tagged tunnel-client release.
The formula installs tunnel-client and its pinned cloudflared companion into
libexec, then exposes only tunnel-client through a wrapper in Homebrew's bin.
Prereleases are rejected unless --allow-prerelease is passed explicitly for a
draft publication test.
EOF
}

die() {
  echo "generate_homebrew_formula.sh: $*" >&2
  exit 1
}

tag=""
checksums=""
output=""
allow_prerelease="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tag)
      tag="${2:-}"
      shift 2
      ;;
    --checksums)
      checksums="${2:-}"
      shift 2
      ;;
    --output)
      output="${2:-}"
      shift 2
      ;;
    --allow-prerelease)
      allow_prerelease="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      die "unknown argument: $1"
      ;;
  esac
done

[[ -n "${tag}" ]] || die "--tag is required"
[[ -n "${checksums}" ]] || die "--checksums is required"
[[ -n "${output}" ]] || die "--output is required"
[[ -f "${checksums}" ]] || die "checksums file does not exist: ${checksums}"

eval "$("${RELEASE_TAG_SCRIPT}" parse "${tag}")"
[[ "${prerelease}" == "false" || "${allow_prerelease}" == "true" ]] ||
  die "prerelease tags do not produce a Homebrew formula"
formula_base_url="${public_base_url%/${release_tag}}/v#{version}"

sha_for() {
  local artifact="$1"
  local matches
  local count
  local sha

  matches="$(awk -v artifact="${artifact}" '$2 == artifact { print $1 }' "${checksums}")"
  count="$(printf '%s\n' "${matches}" | awk 'NF { count += 1 } END { print count + 0 }')"
  [[ "${count}" -eq 1 ]] ||
    die "expected exactly one checksum for ${artifact}, found ${count}"

  sha="${matches}"
  [[ "${sha}" =~ ^[0-9a-f]{64}$ ]] ||
    die "checksum for ${artifact} is not a lowercase SHA-256 digest: ${sha}"
  printf '%s\n' "${sha}"
}

darwin_amd64_asset="tunnel-client-${release_tag}-darwin-amd64.zip"
darwin_arm64_asset="tunnel-client-${release_tag}-darwin-arm64.zip"
linux_amd64_asset="tunnel-client-${release_tag}-linux-amd64.zip"
linux_arm64_asset="tunnel-client-${release_tag}-linux-arm64.zip"

darwin_amd64_sha="$(sha_for "${darwin_amd64_asset}")"
darwin_arm64_sha="$(sha_for "${darwin_arm64_asset}")"
linux_amd64_sha="$(sha_for "${linux_amd64_asset}")"
linux_arm64_sha="$(sha_for "${linux_arm64_asset}")"

mkdir -p "$(dirname "${output}")"
cat > "${output}" <<EOF
# typed: strict
# frozen_string_literal: true

# Generated by tunnel-client release automation. DO NOT EDIT.
class TunnelClient < Formula
  desc "Customer-run agent for Secure MCP Tunnel"
  homepage "https://github.com/openai/tunnel-client"
  version "${release_version}"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "${formula_base_url}/tunnel-client-v#{version}-darwin-amd64.zip"
      sha256 "${darwin_amd64_sha}"
    end
    on_arm do
      url "${formula_base_url}/tunnel-client-v#{version}-darwin-arm64.zip"
      sha256 "${darwin_arm64_sha}"
    end
  end

  on_linux do
    on_intel do
      url "${formula_base_url}/tunnel-client-v#{version}-linux-amd64.zip"
      sha256 "${linux_amd64_sha}"
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "${formula_base_url}/tunnel-client-v#{version}-linux-arm64.zip"
        sha256 "${linux_arm64_sha}"
      end
    end
  end

  def install
    libexec.install "tunnel-client", "cloudflared", "cloudflared-manifest.json"
    bin.write_exec_script libexec/"tunnel-client"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tunnel-client --version")
  end
end
EOF
