package wiretypes

import (
	"encoding/json"
	"errors"
	"net/http"
	"regexp"
	"time"
)

// CommandType is a discriminator for different kinds of polled commands.
type CommandType string

const (
	// CommandTypeJSONRPC indicates a standard JSON-RPC command payload.
	CommandTypeJSONRPC CommandType = "jsonrpc"
	// CommandTypeOAuthDiscovery indicates an OAuth discovery command payload.
	CommandTypeOAuthDiscovery CommandType = "oauth_discovery"
	// CommandTypeSessionTermination indicates an explicit Streamable HTTP session close.
	CommandTypeSessionTermination CommandType = "session_termination"
)

type ResponsePayloadType string

const (
	ResponsePayloadJSONRPC            ResponsePayloadType = "jsonrpc_response"
	ResponsePayloadJSONRPCNotify      ResponsePayloadType = "jsonrpc_notify"
	ResponsePayloadNotifyAck          ResponsePayloadType = "notify_ack"
	ResponsePayloadOAuth              ResponsePayloadType = "oauth_discovery_response"
	ResponsePayloadSessionTermination ResponsePayloadType = "session_termination_response"
)

var (
	responseTimeoutPattern    = regexp.MustCompile(`^[0-9]+(ns|us|ms|s|m|h)$`)
	errInvalidResponseTimeout = errors.New("invalid response timeout")
)

// ResponseTimeoutDuration is an integer value followed by one response-timeout
// unit. Invalid JSON values decode to an invalid empty value so optional timing
// metadata never makes an otherwise valid command unreadable. Callers must use
// Value to distinguish a valid zero duration from invalid metadata.
type ResponseTimeoutDuration string

func (d *ResponseTimeoutDuration) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		*d = ""
		return nil
	}
	if _, err := parseResponseTimeout(value); err != nil {
		*d = ""
		return nil
	}
	*d = ResponseTimeoutDuration(value)
	return nil
}

// Value parses the duration and reports whether the wire value is valid.
func (d ResponseTimeoutDuration) Value() (time.Duration, bool) {
	if d == "" {
		return 0, false
	}
	parsed, err := parseResponseTimeout(string(d))
	if err != nil {
		return 0, false
	}
	return parsed, true
}

func parseResponseTimeout(value string) (time.Duration, error) {
	if !responseTimeoutPattern.MatchString(value) {
		return 0, errInvalidResponseTimeout
	}
	return time.ParseDuration(value)
}

// TunnelResponsePayload mirrors the body posted to POST /v1/tunnels/{tunnel_id}/response when
// delivering MCP results back to tunnel-service.
type TunnelResponsePayload struct {
	RequestID       string              `json:"request_id"`
	Channel         string              `json:"channel,omitempty"`
	JSONResponse    json.RawMessage     `json:"resp_json,omitempty"`
	ResponseHeaders http.Header         `json:"resp_headers,omitempty"`
	ResponseCode    int                 `json:"resp_code,omitempty"`
	ResponseType    ResponsePayloadType `json:"resp_type,omitempty"`
}

// BaseRawPolledCommand contains fields common to all polled command payloads.
// It is embedded by concrete raw command structs for reuse and to keep JSON
// field names stable.
type BaseRawPolledCommand struct {
	RequestID string `json:"request_id"`
	// ShardToken is an opaque value generated by tunnel-service to associate
	// this command with the backend shard or worker responsible for handling
	// its lifecycle. Clients MUST treat this value as opaque and MUST echo
	// it back when posting the response via the HTTP header
	// `X-Tunnel-Shard-Token`. The JSON body of the response MUST NOT contain
	// this token.
	ShardToken string `json:"shard_token"`
	// CommandType is a discriminator for the command payload type.
	CommandType CommandType `json:"command_type"`
	Channel     string      `json:"channel,omitempty"`
	CreatedAt   time.Time   `json:"created_at"`
	Headers     http.Header `json:"headers"`
	// ResponseTimeout is an optional relative duration for the complete command
	// lifecycle, anchored when the poll response is received.
	ResponseTimeout *ResponseTimeoutDuration `json:"response_timeout,omitempty"`
}

// RawJSONRPCPolledCommand represents a single JSON object returned by
// GET /v1/tunnels/{tunnel_id}/poll before it is converted into the strongly typed
// controlplane.PolledCommand interface.
type RawJSONRPCPolledCommand struct {
	BaseRawPolledCommand
	JSONRPC json.RawMessage `json:"jsonrpc"`
}

// Rely on default json marshal/unmarshal for time.Time fields.

// RawOauthDiscoveryPolledCommand represents an OAuth discovery style command.
// It extends the base fields and may include discovery-specific attributes.
type RawOauthDiscoveryPolledCommand struct {
	BaseRawPolledCommand
}

// RawSessionTerminationPolledCommand represents an explicit Streamable HTTP session close.
type RawSessionTerminationPolledCommand struct {
	BaseRawPolledCommand
}

// Rely on default json marshal/unmarshal for time.Time fields.

// PolledCommandEnvelope is the top-level container returned by
// GET /v1/tunnels/{tunnel_id}/poll that groups pending requests for a tunnel.
type PolledCommandEnvelope struct {
	Commands []json.RawMessage `json:"commands"`
}
